-- =============================================================================
-- PushComm Community Edition — CORE baseline schema (migration 0000).
-- Derived from the production schema via pg_dump --schema-only, with add-on
-- tables removed: transcripts, telematics trips/stops, incidents/media
-- (Visual Verification) and app_releases (OTA) are created by the private
-- add-ons' own migration sources, which the runner applies alongside this one
-- (see src/db/migrate.ts).
-- Applying it to an empty database produces the full current schema. Subsequent
-- schema changes go in new numbered files (0001_*.sql, ...) applied by
-- src/db/migrate.ts. Databases that predate this system "adopt" the baseline (it
-- is recorded as applied without re-running). Do NOT edit this file after release.
-- =============================================================================
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
-- (pg_dump's `set_config('search_path','',false)` removed: it would persist an
-- empty search_path on the pooled connection and break later queries. All objects
-- below are schema-qualified, so it is unnecessary.)
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: action_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.action_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    user_id uuid,
    target_type character varying(30),
    target_id uuid,
    action character varying(100) NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: app_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_config (
    key text NOT NULL,
    value text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audio_library; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audio_library (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    filename character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size integer,
    duration numeric(10,2),
    mime_type character varying(100),
    category character varying(20) NOT NULL,
    uploaded_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: call_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.call_attachments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    call_id uuid NOT NULL,
    user_id uuid,
    filename character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size integer,
    mime_type character varying(100),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: call_dispatches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.call_dispatches (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    call_id uuid NOT NULL,
    dispatch_type character varying(20) NOT NULL,
    target_id uuid NOT NULL,
    dispatched_by uuid,
    dispatched_at timestamp with time zone DEFAULT now() NOT NULL,
    acknowledged_at timestamp with time zone,
    on_scene_at timestamp with time zone,
    cleared_at timestamp with time zone
);


--
-- Name: call_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.call_notes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    call_id uuid NOT NULL,
    user_id uuid NOT NULL,
    note text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: calls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    number integer NOT NULL,
    name character varying(255) NOT NULL,
    nature text,
    priority character varying(20) DEFAULT 'medium'::character varying NOT NULL,
    type character varying(100),
    state character varying(20) DEFAULT 'active'::character varying NOT NULL,
    address text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    w3w character varying(100),
    source character varying(50),
    reported_by uuid,
    closed_by uuid,
    closed_at timestamp with time zone,
    dispatch_count integer DEFAULT 0 NOT NULL,
    last_dispatched_at timestamp with time zone,
    form_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: calls_number_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.calls_number_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: calls_number_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.calls_number_seq OWNED BY public.calls.number;


--
-- Name: custom_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_states (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    type character varying(30) NOT NULL,
    name character varying(100) NOT NULL,
    button_text character varying(50) NOT NULL,
    button_color character varying(7) NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: customer_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_locations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    label character varying(120),
    address text NOT NULL,
    latitude numeric(10,8),
    longitude numeric(11,8),
    hours_of_operation text,
    access_notes text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) DEFAULT 'business'::character varying NOT NULL,
    primary_contact_name character varying(255),
    primary_contact_phone character varying(50),
    primary_contact_email character varying(255),
    delivery_notes text,
    tags text,
    is_active boolean DEFAULT true NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    address text,
    city character varying(100),
    state character varying(50),
    zip_code character varying(20)
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    code character varying(50),
    address text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    timezone character varying(50) DEFAULT 'UTC'::character varying NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devices (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    imei character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    model character varying(100),
    assigned_user_id uuid,
    assigned_group_id uuid,
    provisioning_key character varying(64) NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    last_seen_at timestamp with time zone,
    firmware_version character varying(50),
    ip_address character varying(45),
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    provisioning_code_hash character varying(64),
    provisioning_code_expires_at timestamp with time zone,
    provisioned_at timestamp with time zone
);


--
-- Name: geofences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.geofences (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    coordinates jsonb NOT NULL,
    active boolean DEFAULT true NOT NULL,
    assigned_user_ids uuid[],
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_members (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    group_id uuid NOT NULL,
    user_id uuid NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: group_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_types (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    display_name character varying(100) NOT NULL,
    description character varying(255),
    color character varying(7) DEFAULT '#6b7280'::character varying NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    parent_group_id uuid,
    name character varying(255) NOT NULL,
    type character varying(50) DEFAULT 'group'::character varying NOT NULL,
    description text,
    address text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    number integer NOT NULL,
    customer_id uuid NOT NULL,
    customer_location_id uuid,
    job_type character varying(20) DEFAULT 'delivery'::character varying NOT NULL,
    state character varying(20) DEFAULT 'new'::character varying NOT NULL,
    priority character varying(20) DEFAULT 'medium'::character varying NOT NULL,
    notes text,
    assigned_user_id uuid,
    assigned_unit_id uuid,
    assigned_at timestamp with time zone,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: jobs_number_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobs ALTER COLUMN number ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.jobs_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    unit_id uuid,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    altitude numeric(8,2),
    accuracy numeric(8,2),
    speed numeric(8,2),
    heading numeric(5,2),
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    sender_id uuid NOT NULL,
    type character varying(20) DEFAULT 'direct'::character varying NOT NULL,
    target_user_id uuid,
    target_group_id uuid,
    subject character varying(255),
    body text NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    file_path character varying(500),
    file_size integer,
    mime_type character varying(100)
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    permission_type character varying(50) NOT NULL,
    role character varying(20),
    allowed boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: points_of_interest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.points_of_interest (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    radius_meters integer DEFAULT 100 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    assigned_user_ids uuid[],
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: ptt_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ptt_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    room_name character varying(255) NOT NULL,
    channel_id uuid,
    is_private boolean DEFAULT false NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    duration_sec integer,
    max_participant_count integer DEFAULT 0,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    location_lat numeric(10,8),
    location_lon numeric(11,8),
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    display_name character varying(100) NOT NULL,
    description character varying(255),
    hierarchy_level integer DEFAULT 0 NOT NULL,
    color character varying(7) DEFAULT '#6b7280'::character varying NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sos_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sos_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    reported_by uuid NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    acknowledged_by uuid,
    acknowledged_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolution character varying(30),
    resolution_note text,
    resolved_by uuid,
    resolved_at timestamp with time zone
);


--
-- Name: unit_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_states (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unit_id uuid NOT NULL,
    state character varying(50) NOT NULL,
    custom_state_id uuid,
    note text,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    changed_by uuid
);


--
-- Name: units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.units (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    station_group_id uuid,
    name character varying(255) NOT NULL,
    type character varying(50),
    plate_number character varying(50),
    vin character varying(50),
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_states (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    state character varying(50) NOT NULL,
    custom_state_id uuid,
    note text,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    changed_by uuid
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    email character varying(255),
    username character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(50),
    role character varying(20) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    device character varying(100),
    address text,
    city character varying(100),
    notes text,
    state character varying(50),
    zip_code character varying(20),
    fcm_token character varying(512)
);


--
-- Name: voice_channel_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_channel_groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    channel_id uuid NOT NULL,
    group_id uuid NOT NULL
);


--
-- Name: voice_channel_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_channel_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    channel_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: voice_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_channels (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    livekit_room character varying(100) NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: voice_recordings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_recordings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    channel_id uuid,
    call_id uuid,
    source character varying(30) DEFAULT 'live_ptt'::character varying NOT NULL,
    direction character varying(30) DEFAULT 'mixed'::character varying NOT NULL,
    status character varying(20) DEFAULT 'processing'::character varying NOT NULL,
    speaker_user_id uuid,
    speaker_label character varying(255),
    note text,
    file_path character varying(500),
    file_size integer,
    mime_type character varying(100) DEFAULT 'audio/webm'::character varying,
    duration_sec integer,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    egress_id character varying(255),
    ptt_session_id uuid,
    livekit_identity character varying(255),
    target_type character varying(20) DEFAULT 'group'::character varying NOT NULL,
    target_user_id uuid,
    device_id uuid,
    is_sos boolean DEFAULT false NOT NULL,
    capture_error text,
    ended_reason character varying(40),
    target_label text
);


--
-- Name: zone_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zone_alerts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    department_id uuid NOT NULL,
    zone_type character varying(10) NOT NULL,
    zone_id uuid NOT NULL,
    zone_name character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    alert_type character varying(10) NOT NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    triggered_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: calls number; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calls ALTER COLUMN number SET DEFAULT nextval('public.calls_number_seq'::regclass);


--
-- Name: action_logs action_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_logs
    ADD CONSTRAINT action_logs_pkey PRIMARY KEY (id);


--
-- Name: app_config app_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_config
    ADD CONSTRAINT app_config_pkey PRIMARY KEY (key);


--
-- Name: audio_library audio_library_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audio_library
    ADD CONSTRAINT audio_library_pkey PRIMARY KEY (id);


--
-- Name: call_attachments call_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_attachments
    ADD CONSTRAINT call_attachments_pkey PRIMARY KEY (id);


--
-- Name: call_dispatches call_dispatches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_dispatches
    ADD CONSTRAINT call_dispatches_pkey PRIMARY KEY (id);


--
-- Name: call_notes call_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_notes
    ADD CONSTRAINT call_notes_pkey PRIMARY KEY (id);


--
-- Name: calls calls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calls
    ADD CONSTRAINT calls_pkey PRIMARY KEY (id);


--
-- Name: custom_states custom_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_states
    ADD CONSTRAINT custom_states_pkey PRIMARY KEY (id);


--
-- Name: customer_locations customer_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_locations
    ADD CONSTRAINT customer_locations_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: departments departments_code_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_code_unique UNIQUE (code);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: geofences geofences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.geofences
    ADD CONSTRAINT geofences_pkey PRIMARY KEY (id);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (id);


--
-- Name: group_types group_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_types
    ADD CONSTRAINT group_types_pkey PRIMARY KEY (id);


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: points_of_interest points_of_interest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_of_interest
    ADD CONSTRAINT points_of_interest_pkey PRIMARY KEY (id);


--
-- Name: ptt_sessions ptt_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ptt_sessions
    ADD CONSTRAINT ptt_sessions_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sos_events sos_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_events
    ADD CONSTRAINT sos_events_pkey PRIMARY KEY (id);


--
-- Name: unit_states unit_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_states
    ADD CONSTRAINT unit_states_pkey PRIMARY KEY (id);


--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);


--
-- Name: group_members uq_group_members; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT uq_group_members UNIQUE (group_id, user_id);


--
-- Name: permissions uq_permissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT uq_permissions UNIQUE (department_id, permission_type, role);


--
-- Name: voice_channel_groups uq_voice_channel_groups; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_groups
    ADD CONSTRAINT uq_voice_channel_groups UNIQUE (channel_id, group_id);


--
-- Name: voice_channel_users uq_voice_channel_users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_users
    ADD CONSTRAINT uq_voice_channel_users UNIQUE (channel_id, user_id);


--
-- Name: user_states user_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_states
    ADD CONSTRAINT user_states_pkey PRIMARY KEY (id);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_unique UNIQUE (username);


--
-- Name: voice_channel_groups voice_channel_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_groups
    ADD CONSTRAINT voice_channel_groups_pkey PRIMARY KEY (id);


--
-- Name: voice_channel_users voice_channel_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_users
    ADD CONSTRAINT voice_channel_users_pkey PRIMARY KEY (id);


--
-- Name: voice_channels voice_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channels
    ADD CONSTRAINT voice_channels_pkey PRIMARY KEY (id);


--
-- Name: voice_recordings voice_recordings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_pkey PRIMARY KEY (id);


--
-- Name: zone_alerts zone_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_alerts
    ADD CONSTRAINT zone_alerts_pkey PRIMARY KEY (id);


--
-- Name: idx_action_logs_dept_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_action_logs_dept_timestamp ON public.action_logs USING btree (department_id, "timestamp");


--
-- Name: idx_action_logs_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_action_logs_target ON public.action_logs USING btree (target_type, target_id, "timestamp");


--
-- Name: idx_action_logs_user_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_action_logs_user_timestamp ON public.action_logs USING btree (user_id, "timestamp");


--
-- Name: idx_customer_locations_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_locations_customer ON public.customer_locations USING btree (customer_id);


--
-- Name: idx_customer_locations_department; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_locations_department ON public.customer_locations USING btree (department_id);


--
-- Name: idx_customers_department_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customers_department_name ON public.customers USING btree (department_id, name);


--
-- Name: idx_devices_provisioning_code_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_devices_provisioning_code_hash ON public.devices USING btree (provisioning_code_hash) WHERE (provisioning_code_hash IS NOT NULL);


--
-- Name: idx_group_types_dept_name_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_group_types_dept_name_active ON public.group_types USING btree (department_id, name) WHERE (is_deleted = false);


--
-- Name: idx_jobs_assigned_unit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_assigned_unit ON public.jobs USING btree (assigned_unit_id);


--
-- Name: idx_jobs_assigned_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_assigned_user ON public.jobs USING btree (assigned_user_id);


--
-- Name: idx_jobs_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_customer ON public.jobs USING btree (customer_id);


--
-- Name: idx_jobs_department_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_department_state ON public.jobs USING btree (department_id, state);


--
-- Name: idx_locations_unit_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_locations_unit_timestamp ON public.locations USING btree (unit_id, "timestamp");


--
-- Name: idx_locations_user_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_locations_user_timestamp ON public.locations USING btree (user_id, "timestamp");


--
-- Name: idx_ptt_sessions_channel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ptt_sessions_channel ON public.ptt_sessions USING btree (channel_id, started_at);


--
-- Name: idx_ptt_sessions_dept; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ptt_sessions_dept ON public.ptt_sessions USING btree (department_id, started_at);


--
-- Name: idx_sos_dept_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sos_dept_status ON public.sos_events USING btree (department_id, status);


--
-- Name: idx_sos_reported_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sos_reported_by ON public.sos_events USING btree (reported_by, created_at);


--
-- Name: idx_unit_states_unit_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_states_unit_timestamp ON public.unit_states USING btree (unit_id, "timestamp");


--
-- Name: idx_user_states_user_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_states_user_timestamp ON public.user_states USING btree (user_id, "timestamp");


--
-- Name: idx_vcg_channel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vcg_channel ON public.voice_channel_groups USING btree (channel_id);


--
-- Name: idx_vcg_group; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vcg_group ON public.voice_channel_groups USING btree (group_id);


--
-- Name: idx_vcu_channel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vcu_channel ON public.voice_channel_users USING btree (channel_id);


--
-- Name: idx_vcu_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vcu_user ON public.voice_channel_users USING btree (user_id);


--
-- Name: idx_voice_channels_livekit_room; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voice_channels_livekit_room ON public.voice_channels USING btree (livekit_room);


--
-- Name: idx_voice_recordings_call_started; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voice_recordings_call_started ON public.voice_recordings USING btree (call_id, started_at);


--
-- Name: idx_voice_recordings_channel_started; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voice_recordings_channel_started ON public.voice_recordings USING btree (channel_id, started_at);


--
-- Name: idx_voice_recordings_department_started; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voice_recordings_department_started ON public.voice_recordings USING btree (department_id, started_at);


--
-- Name: idx_voice_recordings_sos; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voice_recordings_sos ON public.voice_recordings USING btree (department_id, started_at) WHERE (is_sos = true);


--
-- Name: idx_zone_alerts_dept_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zone_alerts_dept_date ON public.zone_alerts USING btree (department_id, triggered_at);


--
-- Name: idx_zone_alerts_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zone_alerts_user ON public.zone_alerts USING btree (user_id);


--
-- Name: uq_roles_department_name_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_roles_department_name_active ON public.roles USING btree (department_id, name) WHERE (is_deleted = false);


--
-- Name: action_logs action_logs_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_logs
    ADD CONSTRAINT action_logs_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: action_logs action_logs_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_logs
    ADD CONSTRAINT action_logs_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: audio_library audio_library_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audio_library
    ADD CONSTRAINT audio_library_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: audio_library audio_library_uploaded_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audio_library
    ADD CONSTRAINT audio_library_uploaded_by_users_id_fk FOREIGN KEY (uploaded_by) REFERENCES public.users(id);


--
-- Name: call_attachments call_attachments_call_id_calls_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_attachments
    ADD CONSTRAINT call_attachments_call_id_calls_id_fk FOREIGN KEY (call_id) REFERENCES public.calls(id);


--
-- Name: call_attachments call_attachments_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_attachments
    ADD CONSTRAINT call_attachments_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: call_dispatches call_dispatches_call_id_calls_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_dispatches
    ADD CONSTRAINT call_dispatches_call_id_calls_id_fk FOREIGN KEY (call_id) REFERENCES public.calls(id);


--
-- Name: call_dispatches call_dispatches_dispatched_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_dispatches
    ADD CONSTRAINT call_dispatches_dispatched_by_users_id_fk FOREIGN KEY (dispatched_by) REFERENCES public.users(id);


--
-- Name: call_notes call_notes_call_id_calls_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_notes
    ADD CONSTRAINT call_notes_call_id_calls_id_fk FOREIGN KEY (call_id) REFERENCES public.calls(id);


--
-- Name: call_notes call_notes_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_notes
    ADD CONSTRAINT call_notes_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: calls calls_closed_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calls
    ADD CONSTRAINT calls_closed_by_users_id_fk FOREIGN KEY (closed_by) REFERENCES public.users(id);


--
-- Name: calls calls_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calls
    ADD CONSTRAINT calls_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: calls calls_reported_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calls
    ADD CONSTRAINT calls_reported_by_users_id_fk FOREIGN KEY (reported_by) REFERENCES public.users(id);


--
-- Name: custom_states custom_states_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_states
    ADD CONSTRAINT custom_states_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: customer_locations customer_locations_customer_id_customers_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_locations
    ADD CONSTRAINT customer_locations_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: customer_locations customer_locations_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_locations
    ADD CONSTRAINT customer_locations_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: customers customers_created_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: customers customers_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: devices devices_assigned_group_id_groups_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_assigned_group_id_groups_id_fk FOREIGN KEY (assigned_group_id) REFERENCES public.groups(id);


--
-- Name: devices devices_assigned_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_assigned_user_id_users_id_fk FOREIGN KEY (assigned_user_id) REFERENCES public.users(id);


--
-- Name: devices devices_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: geofences geofences_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.geofences
    ADD CONSTRAINT geofences_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: group_members group_members_group_id_groups_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_group_id_groups_id_fk FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- Name: group_members group_members_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: group_types group_types_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_types
    ADD CONSTRAINT group_types_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: groups groups_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: jobs jobs_assigned_unit_id_units_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_assigned_unit_id_units_id_fk FOREIGN KEY (assigned_unit_id) REFERENCES public.units(id);


--
-- Name: jobs jobs_assigned_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_assigned_user_id_users_id_fk FOREIGN KEY (assigned_user_id) REFERENCES public.users(id);


--
-- Name: jobs jobs_created_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: jobs jobs_customer_id_customers_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: jobs jobs_customer_location_id_customer_locations_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_customer_location_id_customer_locations_id_fk FOREIGN KEY (customer_location_id) REFERENCES public.customer_locations(id);


--
-- Name: jobs jobs_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: locations locations_unit_id_units_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_unit_id_units_id_fk FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: locations locations_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: messages messages_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: messages messages_sender_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_sender_id_users_id_fk FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: messages messages_target_group_id_groups_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_target_group_id_groups_id_fk FOREIGN KEY (target_group_id) REFERENCES public.groups(id);


--
-- Name: messages messages_target_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_target_user_id_users_id_fk FOREIGN KEY (target_user_id) REFERENCES public.users(id);


--
-- Name: permissions permissions_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: points_of_interest points_of_interest_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_of_interest
    ADD CONSTRAINT points_of_interest_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: ptt_sessions ptt_sessions_channel_id_voice_channels_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ptt_sessions
    ADD CONSTRAINT ptt_sessions_channel_id_voice_channels_id_fk FOREIGN KEY (channel_id) REFERENCES public.voice_channels(id);


--
-- Name: ptt_sessions ptt_sessions_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ptt_sessions
    ADD CONSTRAINT ptt_sessions_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: roles roles_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: sos_events sos_events_acknowledged_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_events
    ADD CONSTRAINT sos_events_acknowledged_by_users_id_fk FOREIGN KEY (acknowledged_by) REFERENCES public.users(id);


--
-- Name: sos_events sos_events_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_events
    ADD CONSTRAINT sos_events_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: sos_events sos_events_reported_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_events
    ADD CONSTRAINT sos_events_reported_by_users_id_fk FOREIGN KEY (reported_by) REFERENCES public.users(id);


--
-- Name: sos_events sos_events_resolved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_events
    ADD CONSTRAINT sos_events_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id);


--
-- Name: unit_states unit_states_changed_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_states
    ADD CONSTRAINT unit_states_changed_by_users_id_fk FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- Name: unit_states unit_states_custom_state_id_custom_states_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_states
    ADD CONSTRAINT unit_states_custom_state_id_custom_states_id_fk FOREIGN KEY (custom_state_id) REFERENCES public.custom_states(id);


--
-- Name: unit_states unit_states_unit_id_units_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_states
    ADD CONSTRAINT unit_states_unit_id_units_id_fk FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: units units_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: units units_station_group_id_groups_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_station_group_id_groups_id_fk FOREIGN KEY (station_group_id) REFERENCES public.groups(id);


--
-- Name: user_states user_states_changed_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_states
    ADD CONSTRAINT user_states_changed_by_users_id_fk FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- Name: user_states user_states_custom_state_id_custom_states_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_states
    ADD CONSTRAINT user_states_custom_state_id_custom_states_id_fk FOREIGN KEY (custom_state_id) REFERENCES public.custom_states(id);


--
-- Name: user_states user_states_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_states
    ADD CONSTRAINT user_states_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users users_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: voice_channel_groups voice_channel_groups_channel_id_voice_channels_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_groups
    ADD CONSTRAINT voice_channel_groups_channel_id_voice_channels_id_fk FOREIGN KEY (channel_id) REFERENCES public.voice_channels(id);


--
-- Name: voice_channel_groups voice_channel_groups_group_id_groups_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_groups
    ADD CONSTRAINT voice_channel_groups_group_id_groups_id_fk FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- Name: voice_channel_users voice_channel_users_channel_id_voice_channels_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_users
    ADD CONSTRAINT voice_channel_users_channel_id_voice_channels_id_fk FOREIGN KEY (channel_id) REFERENCES public.voice_channels(id);


--
-- Name: voice_channel_users voice_channel_users_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channel_users
    ADD CONSTRAINT voice_channel_users_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: voice_channels voice_channels_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_channels
    ADD CONSTRAINT voice_channels_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: voice_recordings voice_recordings_call_id_calls_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_call_id_calls_id_fk FOREIGN KEY (call_id) REFERENCES public.calls(id);


--
-- Name: voice_recordings voice_recordings_channel_id_voice_channels_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_channel_id_voice_channels_id_fk FOREIGN KEY (channel_id) REFERENCES public.voice_channels(id);


--
-- Name: voice_recordings voice_recordings_created_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: voice_recordings voice_recordings_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: voice_recordings voice_recordings_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id);


--
-- Name: voice_recordings voice_recordings_ptt_session_id_ptt_sessions_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_ptt_session_id_ptt_sessions_id_fk FOREIGN KEY (ptt_session_id) REFERENCES public.ptt_sessions(id);


--
-- Name: voice_recordings voice_recordings_speaker_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_speaker_user_id_users_id_fk FOREIGN KEY (speaker_user_id) REFERENCES public.users(id);


--
-- Name: voice_recordings voice_recordings_target_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_recordings
    ADD CONSTRAINT voice_recordings_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.users(id);


--
-- Name: zone_alerts zone_alerts_department_id_departments_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_alerts
    ADD CONSTRAINT zone_alerts_department_id_departments_id_fk FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: zone_alerts zone_alerts_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_alerts
    ADD CONSTRAINT zone_alerts_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

